server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /datos-gov/ {
        proxy_pass https://www.datos.gov.co/;
        proxy_set_header Host www.datos.gov.co;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }

    error_page 404 /index.html;
}